name: 'Build and release'
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install composer dependencies
        run: composer update --no-dev --prefer-dist

      - name: Build artifacts
        run: |
          mkdir ./multi-crypto-currency-payment
          cp -R -t ./multi-crypto-currency-payment ./assets ./inc ./vendor LICENSE.txt mccp.php readme.txt
          zip -r ./multi-crypto-currency-payment.zip ./multi-crypto-currency-payment
          rm -rf ./multi-crypto-currency-payment

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            multi-crypto-currency-payment.zip

      - name: Build message
        run: |
          get_message()
          {
          cat <<EOF
          Release ${{ github.repository }} has been created. Link: ${{ steps.release.outputs.url }}
          EOF
          }
          
          echo MESSAGE=$(get_message) >> $GITHUB_ENV
